name: Build Android APK

on:
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI
  push:
    branches:
      - main
      - stage
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ github.ref_name == 'stage' && 'stage' || 'production' }}
      EXPO_PUBLIC_API_URL: ${{ github.ref_name == 'stage' && 'https://strava-scout-stage.nmanjuonline.workers.dev' || 'https://strava-scout.nmanjuonline.workers.dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Create google-services.json
        working-directory: ./app
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > google-services.json

      - name: Run Expo Prebuild
        working-directory: ./app
        run: npx expo prebuild --platform android --clean

      - name: Build APK
        working-directory: ./app/android
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/android/app/build/outputs/apk/release/app-release.apk "app/android/app/build/outputs/apk/release/strava-scout.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Strava Scout
          path: "app/android/app/build/outputs/apk/release/strava-scout.apk"
          retention-days: 7
